package com.nebur.teide.tienda.modelo;
// Generated 17-jul-2014 15:57:59 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TiendaTag generated by hbm2java
 */
@Entity
@Table(name="tienda_tag"
    ,catalog="teide2014"
)
public class TiendaTag  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7308309493815284215L;
	private Integer idTag;
     private String nombre;
     private Set<TiendaProducto> tiendaProductos = new HashSet<TiendaProducto>(0);

    public TiendaTag() {
    }

	
    public TiendaTag(String nombre) {
        this.nombre = nombre;
    }
    public TiendaTag(String nombre, Set<TiendaProducto> tiendaProductos) {
       this.nombre = nombre;
       this.tiendaProductos = tiendaProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTag", unique=true, nullable=false)
    public Integer getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="tiendaTags")
    public Set<TiendaProducto> getTiendaProductos() {
        return this.tiendaProductos;
    }
    
    public void setTiendaProductos(Set<TiendaProducto> tiendaProductos) {
        this.tiendaProductos = tiendaProductos;
    }




}


