package com.nebur.teide.tienda.modelo;
// Generated 15-jul-2014 16:39:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TiendaProducto generated by hbm2java
 */
public class TiendaProducto  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4455197794161252547L;
	private Integer idProducto;
     private TiendaCategoria tiendaCategoria;
     private String nombre;
     private String descripcion;
     private String foto;
     private Integer existencias;
     private double precio;
     private Set<TiendaProductoEnvio> tiendaProductoEnvios = new HashSet<TiendaProductoEnvio>(0);
     private Set<TiendaTag> tiendaTags = new HashSet<TiendaTag>(0);

    public TiendaProducto() {
    }

	
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, double precio) {
        this.tiendaCategoria = tiendaCategoria;
        this.nombre = nombre;
        this.precio = precio;
    }
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, String descripcion, String foto, Integer existencias, double precio, Set<TiendaProductoEnvio> tiendaProductoEnvios, Set<TiendaTag> tiendaTags) {
       this.tiendaCategoria = tiendaCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.foto = foto;
       this.existencias = existencias;
       this.precio = precio;
       this.tiendaProductoEnvios = tiendaProductoEnvios;
       this.tiendaTags = tiendaTags;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public TiendaCategoria getTiendaCategoria() {
        return this.tiendaCategoria;
    }
    
    public void setTiendaCategoria(TiendaCategoria tiendaCategoria) {
        this.tiendaCategoria = tiendaCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Integer getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Integer existencias) {
        this.existencias = existencias;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set<TiendaProductoEnvio> getTiendaProductoEnvios() {
        return this.tiendaProductoEnvios;
    }
    
    public void setTiendaProductoEnvios(Set<TiendaProductoEnvio> tiendaProductoEnvios) {
        this.tiendaProductoEnvios = tiendaProductoEnvios;
    }
    public Set<TiendaTag> getTiendaTags() {
        return this.tiendaTags;
    }
    
    public void setTiendaTags(Set<TiendaTag> tiendaTags) {
        this.tiendaTags = tiendaTags;
    }




}


