package com.nebur.teide.tienda.modelo;
// Generated 15-jul-2014 16:39:41 by Hibernate Tools 3.6.0



/**
 * TiendaProductoEnvio generated by hbm2java
 */
public class TiendaProductoEnvio  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1679949584286769083L;
	private TiendaProductoEnvioId id;
     private TiendaProducto tiendaProducto;
     private TiendaEnvio tiendaEnvio;
     private double coste;

    public TiendaProductoEnvio() {
    }

    public TiendaProductoEnvio(TiendaProductoEnvioId id, TiendaProducto tiendaProducto, TiendaEnvio tiendaEnvio, double coste) {
       this.id = id;
       this.tiendaProducto = tiendaProducto;
       this.tiendaEnvio = tiendaEnvio;
       this.coste = coste;
    }
   
    public TiendaProductoEnvioId getId() {
        return this.id;
    }
    
    public void setId(TiendaProductoEnvioId id) {
        this.id = id;
    }
    public TiendaProducto getTiendaProducto() {
        return this.tiendaProducto;
    }
    
    public void setTiendaProducto(TiendaProducto tiendaProducto) {
        this.tiendaProducto = tiendaProducto;
    }
    public TiendaEnvio getTiendaEnvio() {
        return this.tiendaEnvio;
    }
    
    public void setTiendaEnvio(TiendaEnvio tiendaEnvio) {
        this.tiendaEnvio = tiendaEnvio;
    }
    public double getCoste() {
        return this.coste;
    }
    
    public void setCoste(double coste) {
        this.coste = coste;
    }




}


