package com.nebur.teide.tienda.modelo;
// Generated 17-jul-2014 15:57:59 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TiendaProductoEnvio generated by hbm2java
 */
@Entity
@Table(name="tienda_producto-envio"
    ,catalog="teide2014"
)
public class TiendaProductoEnvio  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1679949584286769083L;
	private TiendaProductoEnvioId id;
     private TiendaProducto tiendaProducto;
     private TiendaEnvio tiendaEnvio;
     private double coste;

    public TiendaProductoEnvio() {
    }

    public TiendaProductoEnvio(TiendaProductoEnvioId id, TiendaProducto tiendaProducto, TiendaEnvio tiendaEnvio, double coste) {
       this.id = id;
       this.tiendaProducto = tiendaProducto;
       this.tiendaEnvio = tiendaEnvio;
       this.coste = coste;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idProducto", column=@Column(name="idProducto", nullable=false) ), 
        @AttributeOverride(name="idEnvio", column=@Column(name="idEnvio", nullable=false) ) } )
    public TiendaProductoEnvioId getId() {
        return this.id;
    }
    
    public void setId(TiendaProductoEnvioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false, insertable=false, updatable=false)
    public TiendaProducto getTiendaProducto() {
        return this.tiendaProducto;
    }
    
    public void setTiendaProducto(TiendaProducto tiendaProducto) {
        this.tiendaProducto = tiendaProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEnvio", nullable=false, insertable=false, updatable=false)
    public TiendaEnvio getTiendaEnvio() {
        return this.tiendaEnvio;
    }
    
    public void setTiendaEnvio(TiendaEnvio tiendaEnvio) {
        this.tiendaEnvio = tiendaEnvio;
    }

    
    @Column(name="coste", nullable=false, precision=22, scale=0)
    public double getCoste() {
        return this.coste;
    }
    
    public void setCoste(double coste) {
        this.coste = coste;
    }




}


