package com.nebur.teide.tienda.modelo;
// Generated 15-jul-2014 16:39:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TiendaTag generated by hbm2java
 */
public class TiendaTag  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7308309493815284215L;
	private Integer idTag;
     private String nombre;
     private Set<TiendaProducto> tiendaProductos = new HashSet<TiendaProducto>(0);

    public TiendaTag() {
    }

	
    public TiendaTag(String nombre) {
        this.nombre = nombre;
    }
    public TiendaTag(String nombre, Set<TiendaProducto> tiendaProductos) {
       this.nombre = nombre;
       this.tiendaProductos = tiendaProductos;
    }
   
    public Integer getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<TiendaProducto> getTiendaProductos() {
        return this.tiendaProductos;
    }
    
    public void setTiendaProductos(Set<TiendaProducto> tiendaProductos) {
        this.tiendaProductos = tiendaProductos;
    }




}


