package com.nebur.teide.tienda.modelo;
// Generated 17-jul-2014 15:57:59 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiendaEnvio generated by hbm2java
 */
@Entity
@Table(name="tienda_envio"
    ,catalog="teide2014"
)
public class TiendaEnvio  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4125213017437000997L;
	private Integer idEnvios;
     private String nombre;
     private Set<TiendaProductoEnvio> tiendaProductoEnvios = new HashSet<TiendaProductoEnvio>(0);

    public TiendaEnvio() {
    }

	
    public TiendaEnvio(String nombre) {
        this.nombre = nombre;
    }
    public TiendaEnvio(String nombre, Set<TiendaProductoEnvio> tiendaProductoEnvios) {
       this.nombre = nombre;
       this.tiendaProductoEnvios = tiendaProductoEnvios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEnvios", unique=true, nullable=false)
    public Integer getIdEnvios() {
        return this.idEnvios;
    }
    
    public void setIdEnvios(Integer idEnvios) {
        this.idEnvios = idEnvios;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiendaEnvio")
    public Set<TiendaProductoEnvio> getTiendaProductoEnvios() {
        return this.tiendaProductoEnvios;
    }
    
    public void setTiendaProductoEnvios(Set<TiendaProductoEnvio> tiendaProductoEnvios) {
        this.tiendaProductoEnvios = tiendaProductoEnvios;
    }




}


