package com.nebur.teide.tienda.modelo;
// Generated 15-jul-2014 16:39:41 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TiendaEnvio generated by hbm2java
 */
public class TiendaEnvio  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4125213017437000997L;
	private Integer idEnvios;
     private String nombre;
     private Set<TiendaProductoEnvio> tiendaProductoEnvios = new HashSet<TiendaProductoEnvio>(0);

    public TiendaEnvio() {
    }

	
    public TiendaEnvio(String nombre) {
        this.nombre = nombre;
    }
    public TiendaEnvio(String nombre, Set<TiendaProductoEnvio> tiendaProductoEnvios) {
       this.nombre = nombre;
       this.tiendaProductoEnvios = tiendaProductoEnvios;
    }
   
    public Integer getIdEnvios() {
        return this.idEnvios;
    }
    
    public void setIdEnvios(Integer idEnvios) {
        this.idEnvios = idEnvios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<TiendaProductoEnvio> getTiendaProductoEnvios() {
        return this.tiendaProductoEnvios;
    }
    
    public void setTiendaProductoEnvios(Set<TiendaProductoEnvio> tiendaProductoEnvios) {
        this.tiendaProductoEnvios = tiendaProductoEnvios;
    }




}


