package com.nebur.teide.tienda.modelo;
// Generated 17-jul-2014 15:57:59 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQuery;

/**
 * TiendaProducto generated by hbm2java
 */
@Entity
@Table(name="tienda_producto"
    ,catalog="teide2014"
)
@NamedQuery(name="producto_buscarPorNombre", query="from TiendaProducto p where p.nombre like :texto")
public class TiendaProducto  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4455197794161252547L;
	private Integer idProducto;
     private TiendaCategoria tiendaCategoria;
     private String nombre;
     private String descripcion;
     private String foto;
     private Integer existencias;
     private double precio;
     private Set<TiendaProductoEnvio> tiendaProductoEnvios = new HashSet<TiendaProductoEnvio>(0);
     private Set<TiendaTag> tiendaTags = new HashSet<TiendaTag>(0);

    public TiendaProducto() {
    }

	
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, double precio) {
        this.tiendaCategoria = tiendaCategoria;
        this.nombre = nombre;
        this.precio = precio;
    }
    public TiendaProducto(TiendaCategoria tiendaCategoria, String nombre, String descripcion, String foto, Integer existencias, double precio, Set<TiendaProductoEnvio> tiendaProductoEnvios, Set<TiendaTag> tiendaTags) {
       this.tiendaCategoria = tiendaCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.foto = foto;
       this.existencias = existencias;
       this.precio = precio;
       this.tiendaProductoEnvios = tiendaProductoEnvios;
       this.tiendaTags = tiendaTags;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria", nullable=false)
    public TiendaCategoria getTiendaCategoria() {
        return this.tiendaCategoria;
    }
    
    public void setTiendaCategoria(TiendaCategoria tiendaCategoria) {
        this.tiendaCategoria = tiendaCategoria;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="foto", length=450)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="existencias")
    public Integer getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Integer existencias) {
        this.existencias = existencias;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiendaProducto")
    public Set<TiendaProductoEnvio> getTiendaProductoEnvios() {
        return this.tiendaProductoEnvios;
    }
    
    public void setTiendaProductoEnvios(Set<TiendaProductoEnvio> tiendaProductoEnvios) {
        this.tiendaProductoEnvios = tiendaProductoEnvios;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="tienda_producto_tag", catalog="teide2014", joinColumns = { 
        @JoinColumn(name="idProducto", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idTag", nullable=false, updatable=false) })
    public Set<TiendaTag> getTiendaTags() {
        return this.tiendaTags;
    }
    
    public void setTiendaTags(Set<TiendaTag> tiendaTags) {
        this.tiendaTags = tiendaTags;
    }




}


