package com.nebur.teide.tienda.modelo;
// Generated 17-jul-2014 15:57:59 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TiendaProductoEnvioId generated by hbm2java
 */
@Embeddable
public class TiendaProductoEnvioId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5080400652976251145L;
	private int idProducto;
     private int idEnvio;

    public TiendaProductoEnvioId() {
    }

    public TiendaProductoEnvioId(int idProducto, int idEnvio) {
       this.idProducto = idProducto;
       this.idEnvio = idEnvio;
    }
   


    @Column(name="idProducto", nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


    @Column(name="idEnvio", nullable=false)
    public int getIdEnvio() {
        return this.idEnvio;
    }
    
    public void setIdEnvio(int idEnvio) {
        this.idEnvio = idEnvio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TiendaProductoEnvioId) ) return false;
		 TiendaProductoEnvioId castOther = ( TiendaProductoEnvioId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdEnvio()==castOther.getIdEnvio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProducto();
         result = 37 * result + this.getIdEnvio();
         return result;
   }   


}


